### ISSUE TITLE
Error during `local/tedx-jp/10k_data_prep.sh`

### ISSUE THREAD

**Issue by sw005320** [laboroai/LaboroTVSpeech#1]
When I perform `local/tedx-jp/10k_data_prep.sh`, it was failed with the following error

```
local/tedx-jp/10k_data_prep.sh: All required files exist in tedx-jp.
local/tedx-jp/10k_data_prep.sh: Creating a directory containing all valid subtitle segments.
2020-11-19 20:25:05,588 (make_raw_dir:235) INFO: done making data/tedx-jp-all_raw
fix_data_dir.sh: kept all 273 utterances.
fix_data_dir.sh: old files are kept in data/tedx-jp-all_raw_whole/.backup
patching file data/local/tedx-jp-10k_verbatim.tmp/text_content
Hunk #90 FAILED at 2657.
1 out of 320 hunks FAILED -- saving rejects to file data/local/tedx-jp-10k_verbatim.tmp/text_content.rej
```

It seems that the patch file would be wrong.
Could you let me know how we solve it?

**Comment by hfujihara** [comment]
@sw005320 @eiichiroi
Thank you for pointing out this issue and sending me a pull request.
We have separated TEDxJP-10K part to the difference repository ([https://github.com/laboroai/TEDxJP-10K](https://github.com/laboroai/TEDxJP-10K)), in which we modified the way we reconstruct the corpus to a more robust manner.

**Comment by eiichiroi** [comment]
Great! Thank you for your support! :+1:
