### ISSUE TITLE
Too long utterances in the dev set

### ISSUE THREAD

**Issue by sw005320** [laboroai/LaboroTVSpeech#2]
I found that the dev set includes too long sentences.
I suggest removing such long sentences for the official development data.
My suggestion is to remove utterances for more than 30 seconds (e.g., remove the top 33 utterances from the following list).

```
$ sort -k 2 -nr dump/raw/dev/utt2num_samples | head -n 34
v001_dev_RlFGUdfe 2659360
v001_dev_tVD60s3X 2603200
v001_dev_XcWLZ8Ds 2284800
v001_dev_m3w23nXF 1494400
v001_dev_yhU29kG8 1464960
v001_dev_yIo4ACN1 1390720
v001_dev_rUVXkS0Z 1346560
v001_dev_ebeV3qs8 1223840
v001_dev_PPdlAyGz 1205120
v001_dev_6JZPzq4k 1130560
v001_dev_g8vWy3VB 987040
v001_dev_BYca8AqR 982560
v001_dev_kpypOOpB 966240
v001_dev_fwWvJhdZ 939840
v001_dev_YVVAj1Ml 939520
v001_dev_m9vLDdIr 743520
v001_dev_tvigUeHB 694080
v001_dev_puL8hGoC 689120
v001_dev_eqpJcjYj 681920
v001_dev_IroOq3x7 673920
v001_dev_tbyYEkw2 562240
v001_dev_gt3MQcrd 560160
v001_dev_Xkf0hGjo 527200
v001_dev_yIkO2OlI 522560
v001_dev_xL5OF2nG 515680
v001_dev_dfcYXj1r 506880
v001_dev_YUtqHgLy 504800
v001_dev_bJ4u7YZd 500800
v001_dev_I7fBUbhG 497600
v001_dev_6lwD3FOm 487680
v001_dev_hEaNS9HA 486240
v001_dev_uGKSJThT 483200
v001_dev_5SMfe193 480160
v001_dev_g51KQbqF 479200
```

**Comment by sw005320** [comment]
I add more contexts
- the duration of usual spoken utterances would be less than 30 seconds. I guess the above utterances failed to find appropriate silence regions between utterances due to the VAD error or data preparation error.
- too long sentences make the evaluation too long or require too large memory for some decoding algorithms

**Comment by hfujihara** [comment]
We updated LaboroTVSpeech from v1.0b to v1.0c, in which all the wav files in dev set with more than 30 seconds are deleted, as suggested by @sw005320.
We will soon send updated corpus to the users.
