### ISSUE TITLE
English and Music in TEDxJP 10k corpus

### ISSUE THREAD

**Issue by eiichiroi** [laboroai/LaboroTVSpeech#4]
The TEDxJP 10k corpus contains some inapporopriate data for evaluation of Japanese speech recognition.

In following videos, Japanese people talk in English.
But the corpus uses subtitles that are automatically translated into Japanese.

* [Aj-DXM5Zqms](https://www.youtube.com/watch?v=Aj-DXM5Zqms)
* [Ba5Jl1_JKZY](https://www.youtube.com/watch?v=Ba5Jl1_JKZY)
* [Mc044I55SCY](https://www.youtube.com/watch?v=Mc044I55SCY)

Then, following videos contain some music (corpus uses the interval of music).

* [ydhfjNRFzaM](https://www.youtube.com/watch?v=ydhfjNRFzaM)
* [BLElQZfR_2M](https://www.youtube.com/watch?v=BLElQZfR_2M)
* [TWeYkdIQsk0](https://www.youtube.com/watch?v=TWeYkdIQsk0)
* [Ab-KZT06gR0](https://www.youtube.com/watch?v=Ab-KZT06gR0)
* [gffgHgnEhtA](https://www.youtube.com/watch?v=gffgHgnEhtA)
* [kU9LcoHaFLo](https://www.youtube.com/watch?v=kU9LcoHaFLo)

It may be better to be removed from the corpus.

**Comment by hfujihara** [comment]
@eiichiroi
Thank you for pointing out this issue.

We examined the videos you mentioned and 
- removed English utterances in Aj-DXM5Zqms, Ba5Jl1_JKZY and gffgHgnEhtA
- kept Mc044I55SCY as a part used in our data includes only Japanese utteranes
- Kept ydhfjNRFzaM, BLElQZfR_2M, TWeYkdIQsk0, Ab-KZT06gR0, and kU9LcoHaFLo as, though they are singing voices (or rap), their transcriptions are actually correct.

**Comment by hfujihara** [comment]
The above modification was made in https://github.com/laboroai/TEDxJP-10K as TEDxJP-10K_v1.1 .

**Comment by eiichiroi** [comment]
Thank you!
